### ISSUE TITLE
別のhookスクリプトを登録するときのディレクトリ構造はどうすべきか

### ISSUE THREAD

**Issue by harunbu** [tecotec/samples#7]
PHPとPythonの構文をコミット前に検査するpre-commitを作ったので登録したいです。
@ikmski さんが #5 で作ってくれたファイルとどう同居するべきか、意見をください。

* `git-template/`の下に新しいディレクトリを作って保存する？
* `git-template/hooks/`の下に新しいディレクトリを作って保存する？
* `git-template/hooks/`の下に新しい名前で保存する？
* `git-template/hooks/pre-commit`に追記する？

**Comment by ikmski** [comment]
構文チェック用のスクリプトファイルを作成して、`pre-commit` の中でそのスクリプトを呼び出す
はどうでしょう？
参考：https://github.com/ikmski/dotfiles/tree/master/.git_template/hooks

ブランチのチェックも外に出してもいいかもしれません。

**Comment by tecokimura** [comment]
スクリプトのサンプルにしていく感じかな？　その使い方を.mdでもいいかもね

hooks の下に入れる場合は
> git-template/hooks/の下に新しい名前で保存する？
で check-php.pre-commit とか良いと思います

このディレクトリに入っている方が使う場所とサンプルが置いてある場所が同じだから理解しやすいとも思う

**Comment by choco-kei** [comment]
> git-template/hooks/の下に新しいディレクトリを作って保存する？

こっちですかね。
必要な機能を選んでhookスクリプト側から呼び出す感じで。
適当ですがこんなイメージで。
```sh
commands=('cmd1' 'cmd2' 'cmd3')

for command in ${commands[@]}; do
    sh ./dir/${command}.sh
    ret=$?
    if [ ${ret} -ne 0 ]; then
        exit 1
    fi
done
```

**Comment by tecokimura** [comment]
choco-keiの形にしましょうか

**Comment by harunbu** [comment]
#8 でプルリク出しました。
